### PR TITLE
chore: style-dictionary v4

### PR DESCRIPTION
**Pull request by bennypowers**

### CODE REVIEW

**Comment by bennypowers** [comment]
Current headache:

```
/home/bennyp/Developer/redhat-ux/red-hat-design-tokens/node_modules/json5/lib/parse.js:1110
    const err = new SyntaxError(message)
                ^

SyntaxError: Failed to load or parse JSON or JS Object: JSON5: invalid character 'a' at 1:1
    at syntaxError (/home/bennyp/Developer/redhat-ux/red-hat-design-tokens/node_modules/json5/lib/parse.js:1110:17)
    at invalidChar (/home/bennyp/Developer/redhat-ux/red-hat-design-tokens/node_modules/json5/lib/parse.js:1055:12)
    at Object.value (/home/bennyp/Developer/redhat-ux/red-hat-design-tokens/node_modules/json5/lib/parse.js:309:15)
    at lex (/home/bennyp/Developer/redhat-ux/red-hat-design-tokens/node_modules/json5/lib/parse.js:100:42)
    at Object.parse (/home/bennyp/Developer/redhat-ux/red-hat-design-tokens/node_modules/json5/lib/parse.js:25:17)
    at combineJSON (file:///home/bennyp/Developer/redhat-ux/red-hat-design-tokens/node_modules/style-dictionary/lib/utils/combineJSON.js:111:32)
    at StyleDictionary.extend (file:///home/bennyp/Developer/redhat-ux/red-hat-design-tokens/node_modules/style-dictionary/lib/StyleDictionary.js:293:28) {
  lineNumber: 1,
  columnNumber: 1
}

Node.js v22.6.0
```

**Comment by brianferry** [comment]
@bennypowers - Do we know if this will result in different output for the rhds.tokens.json file or are we thinking the updates are mostly in the transformers layer?

**Comment by bennypowers** [comment]
if i do this right there shouldn't be any changes to the outputs

**Comment by bennypowers** [comment]
@brianferry I used a package called `pkdiff` to compare tarballs from main branch with this one

```
❯ git checkout chore/sdv4
  nvm use
  npm ci
  npm run build
  npm pack
  mv rhds-tokens-2.0.1.tgz rhds-tokens-sdv4.tgz
  git checkout main
  nvm use
  npm ci
  npm run build
  npm pack
  mv rhds-tokens-2.0.1.tgz rhds-tokens-main.tgz
  nvm use v14
  npx pkdiff rhds-tokens-sdv4.tgz rhds-tokens-main.tgz
  nvm use
```

And the result was that the packages are exactly the same :muscle:

**Pull request merged**
