### PR TITLE
feat: theme tokens

### PR DESCRIPTION
**Pull request by bennypowers**
Added theme tokens, for responsive theming.

# IMPORTANT!

:point_right: **PLEASE SEE** https://github.com/RedHat-UX/red-hat-design-system/pull/1792 :point_left: 

## Notes to reviewers

Let's give a think about the new token names. for things like `--rh-color-border-subtle`, it's easy to just chop of the `-on-light|dark` suffix, but for `--rh-color-interactive-blue|purple-lighest|darkest` etc, I had to get a bit creative:

```css
rh-surface#theme-link-demo {
  & a {
    color: var(--rh-color-interactive-blue-normal);
    &:hover,
    &:focus-within
    &:active { color: var(--rh-color-interactive-blue-emphasized); }
    &:visited {
      color: var(--rh-color-interactive-purple-normal);
      &:hover,
      &:focus-within
      &:active { color: var(--rh-color-interactive-purple-emphasized); }
    }
  }
}
```

## TODO
- [x] implement icon and status tokens
- [x] update docs
- [x] ensure css output is legal (no multiple color values)
- [x] ensure editor snippets make sense
- [x] update token syntax to work well with sd's dtcg transforms

### CODE REVIEW

**Review by bennypowers — COMMENTED** [review]
should also implement icon status tokens from https://github.com/RedHat-UX/red-hat-design-tokens/pull/127

**Comment by marionnegp** [comment]
@bennypowers, if you're looking to change up some of the more difficult-to-theme token names, @coreyvickery had some ideas in this [Red Hat Color Usage Reference spreadsheet](https://docs.google.com/spreadsheets/d/1fowJrJJ6HWIYFJNCRW3tRQd85V_heOWBijoTN_tjAAA/edit?gid=1641412828#gid=1641412828). Check out the interactive tokens section, which should help with the theming _and_ would get rid of `purple` and `blue` in the names.

**Comment by bennypowers** [comment]
@marionnegp i see there were some changes to the previously-merged-but-not-yet-released status token names

the spreadsheet has:

```
rh-color-status-danger-on-light
rh-color-status-danger-on-dark
rh-color-status-warning-on-light
rh-color-status-warning-on-dark
rh-color-status-caution-on-light
rh-color-status-caution-on-dark
rh-color-status-neutral-on-light
rh-color-status-neutral-on-dark
rh-color-status-success-on-light
rh-color-status-success-on-dark
rh-color-status-note-on-light
rh-color-status-note-on-dark

```

but the yaml has: danger, warning, default, info, success

Luckily, we haven't yet released any of those, so there's still time to make any necessary changes

Please advise if the spreadsheet is up to date

**Comment by coreyvickery** [comment]
> Please advise if the spreadsheet is up to date

@bennypowers It is now, but with your recent Slack message, I think this can be the last thing the designers work with in that spreadsheet until we all figure out how to work in the repo like you want us to.

**Comment by bennypowers** [comment]
ok @coreyvickery and @marionnegp I think this is ready for review. Please carefully check the deploy preview, especially the colour tokens, and make sure everything's correct.

**Comment by bennypowers** [comment]
@marionnegp @coreyvickery so i think i'll merge this tomorrow and cut a prerelease so we can test this in RHDS. We'll still be able to make any changes we need before officially releasing 2.1

**Pull request merged**
